---
global:
  team: 'qwe' # should be set in service repository
  tier: 'T4' # should be set in service repository
  service: 'service'
  env: 'prod'
  base_cluster: 'prod'
  image: ghcr.io/mccutchen/go-httpbin:latest

vmpodscrape:
  enabled: false

alerts: {}

appDefaults:
  addenv: {}
  replicas:
    prod: 1
    _default: 1
  resources:
    prod:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "1000m"
        memory: "128Mi"
    _default:
      requests:
        cpu: "150m"
        memory: "64Mi"
      limits:
        cpu: "250m"
        memory: "64Mi"
  livenessProbe:
    httpGet:
      path: /
      port: http-app
  readinessProbe:
    httpGet:
      path: /
      port: http-app

deployments:
  - name: app
    command: ['/bin/go-httpbin']
    enabled:
      _default: true
