---
global:
  team: 'qwe' # should be set in service repository
  tier: 'T4' # should be set in service repository
  service: 'service'
  env: 'prod'

deployments:
  - name: app
    command: ['/usr/local/bin/go-httpbin']
    enabled:
      _default: true
